### ISSUE TITLE
error in 3-asm

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [cschin/Peregrine#20]
Hi Jason,
I had an error in the 3-asm assembly stage of Peregrine.
The simple error message was below:

"""
2019-11-19 13:22:08,022 - root - CRITICAL - Error in /share/home/yangzz/anaconda3/envs/peregrine/lib/python3.7/site-packages/pypeflow-2.1.1+git.d63b0e79f5a7b2d370b7de84a890f88271afa476-py3.7.egg/pypeflow/do_task.py with args="{'json_fn': '/share/home/yangzz/projects/1_assembly/1_peregrine_test_run/2_assembly/wd/3-asm/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
"""

And pasting another important message which is found in the 'asm.log' file:

"""
Traceback (most recent call last):
  File "/share/home/yangzz/anaconda3/envs/peregrine/bin/ovlp_to_graph.py", line 4, in <module>
    __import__('pkg_resources').run_script('peregrine-pypy==0.1', 'ovlp_to_graph.py')
  File "/share/home/yangzz/anaconda3/envs/peregrine/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/share/home/yangzz/anaconda3/envs/peregrine/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/share/home/yangzz/anaconda3/envs/peregrine/site-packages/peregrine_pypy-0.1-py3.6.egg/EGG-INFO/scripts/ovlp_to_graph.py", line 1584, in <module>
  File "/share/home/yangzz/anaconda3/envs/peregrine/site-packages/peregrine_pypy-0.1-py3.6.egg/EGG-INFO/scripts/ovlp_to_graph.py", line 1580, in main
  File "/share/home/yangzz/anaconda3/envs/peregrine/site-packages/peregrine_pypy-0.1-py3.6.egg/EGG-INFO/scripts/ovlp_to_graph.py", line 1365, in ovlp_to_graph
  File "/share/home/yangzz/anaconda3/envs/peregrine/site-packages/peregrine_pypy-0.1-py3.6.egg/EGG-INFO/scripts/ovlp_to_graph.py", line 891, in generate_string_graph
AttributeError: 'DiGraph' object has no attribute 'node'
1552.13user 74.37system 27:10.76elapsed 99%CPU (0avgtext+0avgdata 93077216maxresident)k
0inputs+0outputs (0major+54551879minor)pagefaults 0swaps
"""

My command is simple as follows:
printf 'yes' | pg_run.py asm reads.list 28 28 28 28 28 28 28 28 28 --with-consensus --shimmer-r 4 --best_n_ovlp 8

And I was just testing with the CHM13 dataset accessible from the Peregrine bioRxv paper.
Looking forward to your reply.
Zhenzhen

**Comment by cschin** [comment]
See issue #19. The latest docker build (cschin/peregrine:0.1.5.5) and the code in the master branch should have addressed this. Or, you can down-grade you networkx to an earlier versions.

**Comment by zhenzhenyang-psu** [comment]
thank you!

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
